#pragma config(Sensor, in1,    rightLinetracker, sensorLineFollower)
#pragma config(Sensor, in2,    leftLinetracker, sensorLineFollower)
#pragma config(Sensor, dgtl1,  killSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  RightBumper,    sensorTouch)
#pragma config(Sensor, dgtl5,  MiddleBumper,   sensorTouch)
#pragma config(Sensor, dgtl7,  LeftBumper,     sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Challenge 2 - Obstacle Course.

int power = 40;
int threshold = 1900;



task main()
{
    wait1Msec(2000);

        while(SensorValue(killSwitch) == 0)
        {
               if(SensorValue(RightBumper) == 0 && SensorValue (LeftBumper) == 0 && SensorValue (MiddleBumper) == 0)
            {
                // no obstacles, move fwd
                    motor[rightMotor] = power;
                    motor[leftMotor] = power;
            }
            else
            {
              if(SensorValue(RightBumper) == 1 || SensorValue (LeftBumper) == 1 || SensorValue (MiddleBumper) == 1)

          //There is a obstacle, move back then turn 90 degrees to the right to avoid it

              motor(leftMotor) = -power;
              motor(rightMotor) = -power;
              wait1Msec(1000);
              motor(leftMotor) = -power;
              motor(rightMotor) = 0;
              wait1Msec(900);

                }
            }

            if(SensorValue(rightLinetracker) > threshold)
            {
                // right sees black, turn left
                motor[rightMotor] = -power;
                motor[leftMotor]  = -power;
                wait1Msec(1000);
                motor[rightMotor] = power;
                motor[leftMotor]  = -(power);
                wait1Msec(900);
            }
            if(SensorValue(leftLinetracker) < threshold)
            {
                // left sees black, turn right
                motor[rightMotor] = -(power+20);
                motor[leftMotor]  = -(power+20);
                wait1Msec(1500);
                motor[leftMotor] = power;
                motor[rightMotor] = -(power);
                wait1Msec(900);
            }
            else if (SensorValue(rightLinetracker) > threshold &&
                    SensorValue(leftLinetracker) > threshold)
            {
                // if both sees black, execute the following
                if(SensorValue(rightLinetracker) > threshold)
                {
                    // right sees black, turn right
                wait1Msec(1000)
                    motor[rightMotor] = -power;
                    motor[leftMotor]  = -power;
                    wait1Msec(1000);
                    motor[rightMotor] = -power;
                    motor[leftMotor]  = -power;
                    wait1Msec(900);
                }
                if(SensorValue(leftLinetracker) > threshold)
                {
                    // left sees black, turn left
                wait1Msec(1000);
                    motor[rightMotor] = -power;
                    motor[leftMotor]  = -power;
                    wait1Msec(1000);
                    motor[rightMotor] = power;
                    motor[leftMotor]  = -(power-10);
                    wait1Msec(900);
                }
            }
           if (SensorValue(killSwitch) == 1)
                {
                    //killSitch pressed stop all tasks

   motor[leftMotor] = 0;
   motor[rightMotor] = 0;
            }


            }

