#pragma config(Sensor, dgtl1,  killSwitch,     sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task killSwitchPress()
{
    waitUntil(SensorValue(killSwitch) == 1);
    stopAllTasks();
}

task main()
{
    startTask (killSwitchPress);
    while (true)
    {
        motor[rightMotor] = vexRT[Ch2];
        motor[leftMotor] = vexRT[Ch3];
    }
}
