#pragma config(Sensor, dgtl3,  killSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  Bounce,         sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Challenge 4 - Kill switch

int power = 40;    // Set power to 40


task main()
{
    wait1Msec(2000);    //Wait 2 sec before starting code

        while(SensorValue(killSwitch) == 0)    //When the sensor is not pressed do the following codes

            {
                    motor[rightMotor] = power;  // Go foward
                    motor[leftMotor] = power;   // Go foward
      }
            {
                if(SensorValue(killSwitch) == 1)  //If Kill switch is pressed do the following codes
                {
                    motor[rightMotor] = -power;   //Go back
                    motor[leftMotor] = -power;    //Go back
                    wait1Msec(1000)               // Wait 1 sec then stop
                }
              }
          }
