#pragma config(Sensor, in1,    rightSensor,    sensorLineFollower)
#pragma config(Sensor, in2,    leftSensor,     sensorNone)
#pragma config(Sensor, in3,    ,               sensorLineFollower)
#pragma config(Sensor, dgtl1,  killSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  rightSwitch,    sensorTouch)
#pragma config(Sensor, dgtl5,  rightMiddleSwitch, sensorTouch)
#pragma config(Sensor, dgtl9,  leftMiddleSwitch, sensorTouch)
#pragma config(Sensor, dgtl10, leftSwitch,     sensorTouch)
#pragma config(Motor,  port1,           rightMotor,    tmotorVex269_HBridge, openLoop, driveRight)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269_HBridge, openLoop, reversed, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void adjustmentRight(float time)
   {
    motor(rightMotor) = -40;
    motor(leftMotor) = -40;
    wait1Msec(time);
    motor(rightMotor) = -40;
    motor(leftMotor) = 40;
    wait1Msec(500);
   }

void adjustmentLeft(float time)
   {
    motor(rightMotor) = -40;
    motor(leftMotor) = -40;
    wait1Msec(time);
    motor(rightMotor) = 40;
    motor(leftMotor) = -40;
    wait1Msec(500);
   }

task main()
{
    while(true)
    {
        if(SensorValue(rightSwitch)== 1)
        {
            adjustmentLeft(600);
        }

        if(SensorValue(rightMiddleSwitch)== 1)
        {
            adjustmentLeft(300);
        }

        if(SensorValue(leftMiddleSwitch)== 1)
        {
            adjustmentRight(300);
        }

        if(SensorValue(leftSwitch)== 1)
        {
            adjustmentRight(600);
        }

        if(SensorValue(leftMiddleSwitch)&&(rightMiddleSwitch))
        {
            adjustmentRight(600);
        }

	    if(SensorValue(leftSensor) <500 && SensorValue(rightSensor) >2000)
	    {
	        motor(rightMotor) = -100;
	        motor(leftMotor) = -100;
	        wait1Msec(3000);
	        motor(rightMotor) = -100;
	        motor(leftMotor) = 100;
	        wait1Msec(6000);
	    }
	    if(SensorValue(leftSensor) >2000 && SensorValue(rightSensor) >2000)
	    {
	        motor(rightMotor) = -100;
	        motor(leftMotor) = -100;
	        wait1Msec(3000);
	        motor(rightMotor) = 100;
	        motor(leftMotor) = -100;
	        wait1Msec(6000);
	    }
	    else if(SensorValue(killSwitch)==1)
	            {
	               stopAllTasks();
                }
        else
        {
            motor(rightMotor) = 40;
            motor(leftMotor) =40;
        }

}
}
